### ISSUE TITLE
buttons being outlined

### ISSUE THREAD

**Issue by ginxkz** [culturally/CashApp#13]
I have downloaded everything even ran it on my own phone I am just having an issue with what it seems to be highlighted bubbles on the interactive buttons. (I am on a iPhone 11) 
![unnamed-2](https://github.com/culturally/CashApp/assets/140362981/77ed388f-6863-438c-8e19-5b318c5505ca)
![unnamed-3](https://github.com/culturally/CashApp/assets/140362981/eab7329a-e032-4142-b233-fdc4aa7ca9bf)

**Comment by culturally** [comment]
Very weird, i am also running it on iPhone 11 16.6 and don't see this it may be just your iOS version or some iOS settings

**Comment by ginxkz** [comment]
any tips on what in the code could be wrong or what I'm doing wrong 

I downloaded the repo from GitHub then opened in Xcode and from there just ran it on my phone is there any optimization I must do before running in on my phone?

**Comment by culturally** [comment]
Maybe compile it first to IPA and then install it or try to run it in simulator and see if you have same issue

**Comment by ginxkz** [comment]
Im going to do as you stated but before I do so I wanted to provide some images when I put the app I the format or "size of iPhone 14" it fits well and when under the size of iPhone 11 it does not fit properly on the images.

<img width="1710" alt="Screenshot 2024-05-30 at 1 57 40 AM" src="https://github.com/culturally/CashApp/assets/140362981/24edea12-90f9-480e-a543-c596d352949c">
<img width="1710" alt="Screenshot 2024-05-30 at 1 57 53 AM" src="https://github.com/culturally/CashApp/assets/140362981/03a953c6-9db9-4607-9b29-ee8373813193">

**Comment by culturally** [comment]
That may be my mistake i'm using old version of xcode. Get back to me after you try it in simulator.

**Comment by culturally** [comment]
i understand but it’s not always as accurate as it presents that’s why i
want you to run it in simulator

**Comment by ginxkz** [comment]
I am having issues with distribution part of the making the app into an IPA ive watched tutorials but it seems they're all on older versions of Xcode is it possible for you to tell me what version you're on and maybe that can help me

**Comment by ginxkz** [comment]
this is to follow your request to hit you back after I try in simulator this is the result from the simulator on iPhone 11

<img width="1710" alt="Screenshot 2024-05-30 at 12 49 42 PM" src="https://github.com/culturally/CashApp/assets/140362981/f8add051-079f-41b5-870b-3c78b7b375a5">
<img width="1710" alt="Screenshot 2024-05-30 at 12 49 47 PM" src="https://github.com/culturally/CashApp/assets/140362981/91e615e1-2693-425a-967e-b65fac927533">

**Comment by culturally** [comment]
> this is to follow your request to hit you back after I try in simulator this is the result from the simulator on iPhone 11
> 
> 
> 
> <img width="1710" alt="Screenshot 2024-05-30 at 12 49 42 PM" src="https://github.com/culturally/CashApp/assets/140362981/f8add051-079f-41b5-870b-3c78b7b375a5">
> 
> <img width="1710" alt="Screenshot 2024-05-30 at 12 49 47 PM" src="https://github.com/culturally/CashApp/assets/140362981/91e615e1-2693-425a-967e-b65fac927533">
> 
> 

interesting try simulator on iPhone 13 i might've mixed up sources

**Comment by ginxkz** [comment]
sorry to bug you as I am trouble shooting so now I restarted from square one I re downloaded everything and now the app fits to the iPhone 11 screen but the grey text bubble are still appearing on my phone but not on the simulator so it could potentially be my iPhones settings (as for which setting I am unsure)

**Comment by culturally** [comment]
> sorry to bug you as I am trouble shooting so now I restarted from square one I re downloaded everything and now the app fits to the iPhone 11 screen but the grey text bubble are still appearing on my phone but not on the simulator so it could potentially be my iPhones settings (as for which setting I am unsure)

then it's most likely your iOS settings issue because i have used it and it don't see them on nmy device and neither in simulator so maybe change some settings

**Comment by ginxkz** [comment]
is it possible that you could help me personally on discord or something of such to run me through the instillation steps I could screen share

**Comment by ginxkz** [comment]
never mind I fixed it thank the lord you were right under accessibility the option called button shapes made the boxes appear
